services:
  mysql-db:
    image: mysql:9.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: listcharacters
      MYSQL_ROOT_PASSWORD: gojo
    ports:
      - "3306:3306" # mappa la porta del container alla stessa porta di codespace
    networks:
      - app-network

  # spring-backend:

networks:
  app-network:
    driver: bridge