spring.application.name=listcharacters

# caricamento delle variabili d'ambiente
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:listcharacters}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:gojo}

# configurazioni per JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true