spring.application.name=listcharacters

# setup connessione database
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:listcharacters}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:gojo}

# configurazioni per JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# configurazioni per multipart upload
spring.servlet.multipart.enabled=true
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# serve per il redirect 
server.forward-headers-strategy=framework

# serve per far si che html utilizzi il linguaggio UTF-8
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# setta la porta del server sulla 8080
server.port=8087
